// Package declaration, defines the namespace for the class
package com.example.thenotesapp.model

// Import statement to include Parcelable, which is used to serialize a class so its properties can be transferred between Android components
import android.os.Parcelable

// Import statement to include Room's Entity annotation, which indicates that this class represents a table in the database
import androidx.room.Entity

// Import statement to include Room's PrimaryKey annotation, which indicates the primary key field of the table
import androidx.room.PrimaryKey

// Import statement to include Parcelize, which is used to simplify the implementation of Parcelable interface
import kotlinx.parcelize.Parcelize

// Entity annotation to mark this data class as a table named "notes" in the Room database
@Entity(tableName = "notes")

// Parcelize annotation to automatically generate the Parcelable implementation for the data class
@Parcelize

// Data class definition for Note, which is a blueprint for creating note objects
data class Note(
    // PrimaryKey annotation to indicate that 'id' is the primary key for this table
    // autoGenerate = true means the value of 'id' will be automatically generated by the database
    @PrimaryKey(autoGenerate = true)
    val id: Int,

    // Property to store the title of the note
    val noteTitle: String,

    // Property to store the description of the note
    val noteDesc: String

// Parcelable implementation to allow Note objects to be passed between Android components
) : Parcelable
